version: '3.8'
services:
  node_app:
    image: haze
    container_name: node_app_container
    working_dir: /app
    volumes:
      - .:/app
    command: npm start
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app_network

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: db_container
    volumes:
      - books_data:/db
    networks:
      - app_network

volumes:
  books_data:

networks:
  app_network:
